version: '2'
services:
  wordpress:
    image: 'wpregistry.mdu.com/mdur-wordpress:w4.8v3'
    depends_on:
      - db
    volumes:
      - 'data:/var/www/html'
  db:
    image: 'mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - 'db:/var/lib/mysql'
  lb:
    image: 'rancher/lb-service-haproxy'
    ports:
      - 8001:8001
    labels:
      io.rancher.scheduler.global: 'true'
volumes:
  data:
    driver: pxd
  db:
    driver: pxd