wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
    
lb:
  image: rancher/lb-service-haproxy
  ports:
    - ${public_port}:${public_port}
volumes:
  ${db_volume}:
    driver: ${volume_driver}
  ${data_volume}:
    driver: ${volume_driver}