version: '2'
services:
  wordpress:
    image: wordpress
    links:
      - db:mysql
    volumes:
      - data:/var/www/html
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
  lb:
    image: rancher/lb-service-haproxy
    ports:
      - ${public_port}:${public_port}
volumes:
  data:
    driver: ${volume_driver}
  db:
    driver: ${volume_driver}